version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      exclude:
        - "org.jboss.da:*"
        - "org.jboss.pnc*:*"        # match org.jboss.pnc:xyz and org.jboss.pnc.group:xyz

  - package-ecosystem: "github-actions" # Also update Github actions
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/"
    # Explicitly specify Dockerfile.jvm if it sits in a custom location or root
    target-files:
      - "src/main/docker/Dockerfile.jvm"
    schedule:
      interval: "weekly"
